# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb/fraud_detection/fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.utils/pb/fraud_detection/fraud_detection.proto\x12\x05hello\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t\"\xc0\x01\n\x15\x46raudDetectionRequest\x12\r\n\x05items\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x13\n\x0b\x63redit_card\x18\x03 \x01(\t\x12\x14\n\x0cuser_comment\x18\x04 \x01(\t\x12\x17\n\x0f\x62illing_address\x18\x05 \x01(\t\x12\x17\n\x0fshipping_method\x18\x06 \x01(\t\x12\x15\n\rgift_wrapping\x18\x07 \x01(\t\x12\x16\n\x0eterms_accepted\x18\x08 \x01(\t\"*\n\x16\x46raudDetectionResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32\x45\n\x0cHelloService\x12\x35\n\x08SayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse2c\n\x15\x46raudDetectionService\x12J\n\x0b\x44\x65tectFraud\x12\x1c.hello.FraudDetectionRequest\x1a\x1d.hello.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.fraud_detection.fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=57
  _globals['_HELLOREQUEST']._serialized_end=85
  _globals['_HELLORESPONSE']._serialized_start=87
  _globals['_HELLORESPONSE']._serialized_end=120
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=123
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=315
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=317
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=359
  _globals['_HELLOSERVICE']._serialized_start=361
  _globals['_HELLOSERVICE']._serialized_end=430
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=432
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
