syntax = "proto3";

package books_database;

service BooksDatabaseService {
	rpc Read (ReadRequest) returns (ReadResponse);
	rpc Write (WriteRequest) returns (WriteResponse);
	rpc IncrementStock (WriteRequest) returns (WriteResponse);
	rpc DecrementStock (WriteRequest) returns (WriteResponse);

	rpc Prepare(PrepareRequest) returns (PrepareResponse);
  rpc Commit(CommitRequest) returns (CommitResponse);
  rpc Abort(AbortRequest) returns (AbortResponse);
}

message ReadRequest {
	string title = 1;
}

message ReadResponse {
	int32 stock = 1;
}

message WriteRequest {
	string title = 1;
	int32 new_stock = 2;
}

message WriteResponse {
	bool success = 1;
}

message PrepareRequest {
	string order_id = 1;
	string title = 2;
	int32 stock = 3;
}

message PrepareResponse {
	bool ready = 1;
}

message CommitRequest {
	string order_id = 1;
}

message CommitResponse {
	bool success = 1;
}

message AbortRequest {
	string order_id = 1;
}

message AbortResponse {
	bool aborted = 1;
}