{
 "title": "ds-practice",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Active Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_queue_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fraudulent v. Total Orders (%)",
   "type": "timeseries",
   "description": "% of fraud orders",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "orders_total", "legendFormat": "__auto" },
    { "expr": "fraud_orders_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Fraudulent Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "fraud_orders_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Checkout Requests",
   "type": "timeseries",
   "description": "Every time /checkout is called",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "orders_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders Queued (past 5 min)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "f67bd31f", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "orchestrator" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "/order_queue.OrderQueueService/Enqueue"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Order Queue Dequeue Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "776c3990", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "order_queue" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "/order_queue.OrderQueueService/Dequeue"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total Fraudulent Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "fraud_orders_total", "legendFormat": "__auto" }
   ]
  }
 ]
}