# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\xdb\x01\n\x1eTransactionVerificationRequest\x12,\n\x04user\x18\x01 \x01(\x0b\x32\x1e.transaction_verification.User\x12\x39\n\x0b\x63redit_card\x18\x02 \x01(\x0b\x32$.transaction_verification.CreditCard\x12\x14\n\x0cuser_comment\x18\x03 \x01(\t\x12:\n\x0f\x62illing_address\x18\x04 \x01(\x0b\x32!.transaction_verification.Address\"6\n\x1fTransactionVerificationResponse\x12\x13\n\x0bis_verified\x18\x01 \x01(\x08\"#\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"B\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"T\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t2\xab\x01\n\x1eTransactionVerificationService\x12\x88\x01\n\x11VerifyTransaction\x12\x38.transaction_verification.TransactionVerificationRequest\x1a\x39.transaction_verification.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=61
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=280
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=282
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=336
  _globals['_USER']._serialized_start=338
  _globals['_USER']._serialized_end=373
  _globals['_CREDITCARD']._serialized_start=375
  _globals['_CREDITCARD']._serialized_end=441
  _globals['_ADDRESS']._serialized_start=443
  _globals['_ADDRESS']._serialized_end=527
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=530
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=701
# @@protoc_insertion_point(module_scope)
