# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\x98\x02\n\x1eTransactionVerificationRequest\x12,\n\x04user\x18\x01 \x01(\x0b\x32\x1e.transaction_verification.User\x12\x39\n\x0b\x63redit_card\x18\x02 \x01(\x0b\x32$.transaction_verification.CreditCard\x12\x14\n\x0cuser_comment\x18\x03 \x01(\t\x12:\n\x0f\x62illing_address\x18\x04 \x01(\x0b\x32!.transaction_verification.Address\x12;\n\x0cvector_clock\x18\x05 \x01(\x0b\x32%.transaction_verification.VectorClock\"s\n\x1fTransactionVerificationResponse\x12\x13\n\x0bis_verified\x18\x01 \x01(\x08\x12;\n\x0cvector_clock\x18\x02 \x01(\x0b\x32%.transaction_verification.VectorClock\"#\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"B\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"T\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"|\n\x0bVectorClock\x12?\n\x05\x63lock\x18\x01 \x03(\x0b\x32\x30.transaction_verification.VectorClock.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\xab\x01\n\x1eTransactionVerificationService\x12\x88\x01\n\x11VerifyTransaction\x12\x38.transaction_verification.TransactionVerificationRequest\x1a\x39.transaction_verification.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._options = None
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=61
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=341
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=343
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=458
  _globals['_USER']._serialized_start=460
  _globals['_USER']._serialized_end=495
  _globals['_CREDITCARD']._serialized_start=497
  _globals['_CREDITCARD']._serialized_end=563
  _globals['_ADDRESS']._serialized_start=565
  _globals['_ADDRESS']._serialized_end=649
  _globals['_VECTORCLOCK']._serialized_start=651
  _globals['_VECTORCLOCK']._serialized_end=775
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_start=731
  _globals['_VECTORCLOCK_CLOCKENTRY']._serialized_end=775
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=778
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
