# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import executor_pb2 as executor__pb2


class ExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/order_queue.ExecutorService/ping',
                request_serializer=executor__pb2.PingRequest.SerializeToString,
                response_deserializer=executor__pb2.PingResponse.FromString,
                )
        self.answer = channel.unary_unary(
                '/order_queue.ExecutorService/answer',
                request_serializer=executor__pb2.Ping.SerializeToString,
                response_deserializer=executor__pb2.PingResponse.FromString,
                )
        self.new_leader = channel.unary_unary(
                '/order_queue.ExecutorService/new_leader',
                request_serializer=executor__pb2.NewLeaderRequest.SerializeToString,
                response_deserializer=executor__pb2.NewLeaderResponse.FromString,
                )


class ExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def new_leader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=executor__pb2.PingRequest.FromString,
                    response_serializer=executor__pb2.PingResponse.SerializeToString,
            ),
            'answer': grpc.unary_unary_rpc_method_handler(
                    servicer.answer,
                    request_deserializer=executor__pb2.Ping.FromString,
                    response_serializer=executor__pb2.PingResponse.SerializeToString,
            ),
            'new_leader': grpc.unary_unary_rpc_method_handler(
                    servicer.new_leader,
                    request_deserializer=executor__pb2.NewLeaderRequest.FromString,
                    response_serializer=executor__pb2.NewLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_queue.ExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_queue.ExecutorService/ping',
            executor__pb2.PingRequest.SerializeToString,
            executor__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_queue.ExecutorService/answer',
            executor__pb2.Ping.SerializeToString,
            executor__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def new_leader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_queue.ExecutorService/new_leader',
            executor__pb2.NewLeaderRequest.SerializeToString,
            executor__pb2.NewLeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
