# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x0border_queue\"\x1e\n\x0bPingRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x05\"\x06\n\x04Ping\"#\n\x0cPingResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\"%\n\x10NewLeaderRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\")\n\x11NewLeaderResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xd3\x01\n\x0f\x45xecutorService\x12;\n\x04ping\x12\x18.order_queue.PingRequest\x1a\x19.order_queue.PingResponse\x12\x36\n\x06\x61nswer\x12\x11.order_queue.Ping\x1a\x19.order_queue.PingResponse\x12K\n\nnew_leader\x12\x1d.order_queue.NewLeaderRequest\x1a\x1e.order_queue.NewLeaderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=31
  _globals['_PINGREQUEST']._serialized_end=61
  _globals['_PING']._serialized_start=63
  _globals['_PING']._serialized_end=69
  _globals['_PINGRESPONSE']._serialized_start=71
  _globals['_PINGRESPONSE']._serialized_end=106
  _globals['_NEWLEADERREQUEST']._serialized_start=108
  _globals['_NEWLEADERREQUEST']._serialized_end=145
  _globals['_NEWLEADERRESPONSE']._serialized_start=147
  _globals['_NEWLEADERRESPONSE']._serialized_end=188
  _globals['_EXECUTORSERVICE']._serialized_start=191
  _globals['_EXECUTORSERVICE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
